/-
Copyright (c) 2026 Iliad. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: stephan@iliad.ac
-/

import Gacs_Chapter_2.Randomness.UniversalContSemimeasure

/-!
# Gács Definition 2.3.36 and Proposition 2.3.37: `KM` versus `K`

`KM(x) = −log M(x)`; we keep `M` itself and state the bounds multiplicatively:

  `2^{-K(x)} ≤ 2^c · M(x)`   and   `M(x) · 2^{-K(|x|)} ≤ 2^c · 2^{-K(x)}`,

i.e. `KM ≤⁺ K ≤⁺ KM + K(|x|)`.

* First bound: `μ(x) = ∑_{y ⊒ x} 2^{-K(y)}` (`extSum`) is a lower semicomputable continuous
  semimeasure with `μ ≥ 2^{-K}`, so `M ≥ 2^{-c} μ`.
* Second bound: `ν(x) = M(x) · 2^{-K(|x|)}` is a lower semicomputable *discrete*
  semimeasure (`∑_x ν(x) = ∑_n 2^{-K(n)} ∑_{|x| = n} M(x) ≤ ∑_n 2^{-K(n)} ≤ 1`), so the coding
  theorem gives `2^{-K} ≥ 2^{-c} ν`.
-/

namespace Kolmogorov.Randomness

open scoped ENNReal

/-! ### The continuous semimeasure generated by a discrete one -/

/-- `∑_{y ⊒ x} m(y)`. -/
noncomputable def extSum (m : BitString → ℝ≥0∞) (x : BitString) : ℝ≥0∞ :=
  ∑' y, if x <+: y then m y else 0

theorem le_extSum (m : BitString → ℝ≥0∞) (x : BitString) : m x ≤ extSum m x := by
  have := ENNReal.le_tsum (f := fun y ↦ if x <+: y then m y else 0) x
  unfold extSum
  simpa using this

theorem extSum_isContSemimeasure {m : BitString → ℝ≥0∞} (hm : IsSemimeasure m) :
    IsContSemimeasure (extSum m) := by
  refine ⟨?_, fun x ↦ ?_⟩
  · calc extSum m [] = ∑' y, m y := tsum_congr (fun y ↦ if_pos (List.nil_prefix))
      _ ≤ 1 := hm
  · unfold extSum
    rw [← ENNReal.tsum_add]
    refine ENNReal.tsum_le_tsum fun y ↦ ?_
    by_cases h0 : x ++ [false] <+: y
    · have hx : x <+: y := (List.prefix_append x [false]).trans h0
      have h1 : ¬ x ++ [true] <+: y := by
        intro h1
        have := List.prefix_of_prefix_length_le h0 h1 (by simp)
        have := this.eq_of_length (by simp)
        simp at this
      rw [if_pos h0, if_neg h1, if_pos hx, add_zero]
    · rw [if_neg h0, zero_add]
      by_cases h1 : x ++ [true] <+: y
      · rw [if_pos h1, if_pos ((List.prefix_append x [true]).trans h1)]
      · rw [if_neg h1]; exact zero_le

/-- Stage-`s` lower approximation of `extSum`. -/
def extSumApprox (a : ℕ → BitString → ℕ) (s : ℕ) (x : BitString) : ℕ :=
  ∑ i ∈ Finset.range (boundedPrograms s).length,
    if ((boundedPrograms s).getD i []).take x.length = x then a s ((boundedPrograms s).getD i [])
    else 0

theorem take_eq_iff_prefix (x y : BitString) : y.take x.length = x ↔ x <+: y := by
  rw [List.prefix_iff_eq_take]; exact eq_comm

theorem extSumApprox_computable {a : ℕ → BitString → ℕ}
    (ha : Computable (fun p : ℕ × BitString ↦ a p.1 p.2)) :
    Computable (fun p : ℕ × BitString ↦ extSumApprox a p.1 p.2) := by
  have hget : Computable (fun q : (ℕ × BitString) × ℕ ↦ (boundedPrograms q.1.1).getD q.2 []) :=
    ((Primrec.list_getD ([] : BitString)).comp
      (primrec_boundedPrograms.comp (Primrec.fst.comp Primrec.fst)) Primrec.snd).to_comp
  have htest : Computable (fun q : (ℕ × BitString) × ℕ ↦
      decide (((boundedPrograms q.1.1).getD q.2 []).take q.1.2.length = q.1.2)) :=
    (bitStringEq_primrec.to_comp.comp (Computable.pair
      (primrec_list_take.to_comp.comp hget
        (Computable.list_length.comp (Computable.snd.comp Computable.fst)))
      (Computable.snd.comp Computable.fst))).of_eq (fun _ ↦ rfl)
  have hval : Computable (fun q : (ℕ × BitString) × ℕ ↦
      a q.1.1 ((boundedPrograms q.1.1).getD q.2 [])) :=
    ha.comp (Computable.pair (Computable.fst.comp Computable.fst) hget)
  have h2 : Computable₂ (fun (p : ℕ × BitString) (i : ℕ) ↦
      if ((boundedPrograms p.1).getD i []).take p.2.length = p.2
        then a p.1 ((boundedPrograms p.1).getD i []) else 0) := by
    have : Computable (fun q : (ℕ × BitString) × ℕ ↦
        if ((boundedPrograms q.1.1).getD q.2 []).take q.1.2.length = q.1.2
          then a q.1.1 ((boundedPrograms q.1.1).getD q.2 []) else 0) :=
      (Computable.cond htest hval (Computable.const 0)).of_eq (fun _ ↦ Bool.cond_decide _ _ _)
    exact this
  exact (computable_range_sum _ h2 (fun p ↦ (boundedPrograms p.1).length)
    ((Primrec.list_length.comp (primrec_boundedPrograms.comp Primrec.fst)).to_comp)).of_eq
    (fun _ ↦ rfl)

theorem dyadic_extSumApprox (a : ℕ → BitString → ℕ) (s : ℕ) (x : BitString) :
    dyadicValue (extSumApprox a s x) s
      = ∑ y ∈ (boundedPrograms s).toFinset, if x <+: y then dyadicValue (a s y) s else 0 := by
  unfold dyadicValue extSumApprox
  rw [sum_range_getD_eq _ (boundedPrograms_nodup s)
    (fun y ↦ if y.take x.length = x then a s y else 0), Nat.cast_sum]
  simp only [div_eq_mul_inv, Finset.sum_mul]
  refine Finset.sum_congr rfl (fun y _ ↦ ?_)
  by_cases h : x <+: y
  · rw [if_pos ((take_eq_iff_prefix x y).mpr h), if_pos h]
  · rw [if_neg (fun h' ↦ h ((take_eq_iff_prefix x y).mp h')), if_neg h]
    simp

/-- **`extSum` of an lsc function is lsc.** -/
theorem extSum_isLSC₁ {m : BitString → ℝ≥0∞} (hm : IsLSC₁ m) : IsLSC₁ (extSum m) := by
  obtain ⟨a, hmono, hsup, ha⟩ := hm
  have hle : ∀ s y, dyadicValue (a s y) s ≤ m y := fun s y ↦ by
    rw [← hsup y]; exact le_iSup (fun s ↦ dyadicValue (a s y) s) s
  refine ⟨extSumApprox a, fun s x ↦ ?_, fun x ↦ ?_, extSumApprox_computable ha⟩
  · rw [dyadic_extSumApprox, dyadic_extSumApprox]
    calc ∑ y ∈ (boundedPrograms s).toFinset, (if x <+: y then dyadicValue (a s y) s else 0)
        ≤ ∑ y ∈ (boundedPrograms s).toFinset,
            (if x <+: y then dyadicValue (a (s + 1) y) (s + 1) else 0) :=
          Finset.sum_le_sum (fun y _ ↦ by split_ifs <;> simp [hmono s y])
      _ ≤ _ := Finset.sum_le_sum_of_subset (fun y hy ↦ by
          rw [List.mem_toFinset, mem_boundedPrograms_iff] at hy ⊢; omega)
  · simp only [dyadic_extSumApprox]
    unfold extSum
    apply le_antisymm
    · refine iSup_le fun s ↦ ?_
      calc ∑ y ∈ (boundedPrograms s).toFinset, (if x <+: y then dyadicValue (a s y) s else 0)
          ≤ ∑ y ∈ (boundedPrograms s).toFinset, (if x <+: y then m y else 0) :=
            Finset.sum_le_sum (fun y _ ↦ by split_ifs <;> simp [hle s y])
        _ ≤ ∑' y, (if x <+: y then m y else 0) := ENNReal.sum_le_tsum _
    · rw [ENNReal.tsum_eq_iSup_sum]
      refine iSup_le fun F ↦ ?_
      set N := F.sup List.length with hN
      have hmonoY : ∀ y, Monotone (fun s ↦ if x <+: y then dyadicValue (a s y) s else 0) := by
        intro y
        refine monotone_nat_of_le_succ (fun s ↦ ?_)
        split_ifs <;> simp [hmono s y]
      have hsupY : ∀ y, (⨆ s, if x <+: y then dyadicValue (a s y) s else 0)
          = if x <+: y then m y else 0 := by
        intro y
        split_ifs
        · exact hsup y
        · exact iSup_const
      calc ∑ y ∈ F, (if x <+: y then m y else 0)
          ≤ ∑ y ∈ (boundedPrograms N).toFinset, (if x <+: y then m y else 0) :=
            Finset.sum_le_sum_of_subset (subset_boundedPrograms F)
        _ = ⨆ s, ∑ y ∈ (boundedPrograms N).toFinset,
              (if x <+: y then dyadicValue (a s y) s else 0) := by
            rw [← ENNReal.finsetSum_iSup_of_monotone hmonoY]
            exact Finset.sum_congr rfl (fun y _ ↦ (hsupY y).symm)
        _ ≤ ⨆ s, ∑ y ∈ (boundedPrograms s).toFinset,
              (if x <+: y then dyadicValue (a s y) s else 0) := by
            refine iSup_le fun s ↦ le_iSup_of_le (max s N) ?_
            calc ∑ y ∈ (boundedPrograms N).toFinset, (if x <+: y then dyadicValue (a s y) s else 0)
                ≤ ∑ y ∈ (boundedPrograms N).toFinset,
                    (if x <+: y then dyadicValue (a (max s N) y) (max s N) else 0) :=
                  Finset.sum_le_sum (fun y _ ↦ hmonoY y (le_max_left s N))
              _ ≤ _ := Finset.sum_le_sum_of_subset (fun y hy ↦ by
                  rw [List.mem_toFinset, mem_boundedPrograms_iff] at hy ⊢
                  exact hy.trans (le_max_right s N))

/-! ### Proposition 2.3.37, first bound: `KM ≤⁺ K` -/

/-- **`2^{-K(x)} ≤ 2^c · M(x)`** for a universal continuous semimeasure `M`. -/
theorem prefixComplexityWeight_le_univ {M : BitString → ℝ≥0∞} (hM : IsUniversalContSemimeasure M)
    (U : Map) (hU : IsOptimalPrefixConditional U) :
    ∃ c : ℕ, ∀ x, prefixComplexityWeight U x ≤ 2 ^ c * M x := by
  have hsemi : IsSemimeasure (prefixComplexityWeight U) := KP_kraft_sum_le_one U hU.isPrefixDecompressor []
  obtain ⟨c, hc⟩ := hM.2.2 (extSum (prefixComplexityWeight U)) (extSum_isContSemimeasure hsemi)
    (extSum_isLSC₁ (prefixComplexityWeight_isLSC₁ U hU.isDecompressor))
  refine ⟨c, fun x ↦ ?_⟩
  calc prefixComplexityWeight U x ≤ extSum (prefixComplexityWeight U) x := le_extSum _ x
    _ = 2 ^ c * (2⁻¹ ^ c * extSum (prefixComplexityWeight U) x) := by
        rw [← mul_assoc, ← ENNReal.inv_pow, ENNReal.mul_inv_cancel (two_pow_ne_zero' c) (two_pow_ne_top' c),
          one_mul]
    _ ≤ 2 ^ c * M x := by gcongr; exact hc x

/-! ### Proposition 2.3.37, second bound: `K ≤⁺ KM + K(|x|)` -/

/-- Regrouping a sum over strings by length, bounded through a continuous semimeasure. -/
theorem tsum_mul_length_weight_le {M : BitString → ℝ≥0∞} (hM : IsContSemimeasure M) (w : ℕ → ℝ≥0∞) :
    ∑' x, M x * w x.length ≤ ∑' n, w n := by
  classical
  calc ∑' x, M x * w x.length
      = ∑' x, ∑' n, (if x.length = n then M x * w n else 0) := by
        refine tsum_congr fun x ↦ ?_
        rw [tsum_eq_single x.length (fun n hn ↦ if_neg (fun h ↦ hn h.symm)), if_pos rfl]
    _ = ∑' n, ∑' x, (if x.length = n then M x * w n else 0) := ENNReal.tsum_comm
    _ = ∑' n, w n * ∑' x, (if x.length = n then M x else 0) := by
        refine tsum_congr fun n ↦ ?_
        rw [← ENNReal.tsum_mul_left]
        refine tsum_congr fun x ↦ ?_
        split_ifs <;> simp [mul_comm]
    _ ≤ ∑' n, w n * 1 := by
        refine ENNReal.tsum_le_tsum fun n ↦ mul_le_mul' le_rfl ?_
        rw [tsum_eq_sum (s := ext [] n) (fun x hx ↦ by
          rw [if_neg]; intro h; exact hx (mem_ext.mpr ⟨List.nil_prefix, by simpa using h⟩))]
        calc ∑ x ∈ ext [] n, (if x.length = n then M x else 0) = ∑ x ∈ ext [] n, M x :=
              Finset.sum_congr rfl (fun x hx ↦ if_pos (ext_zero_length n hx))
          _ ≤ M [] := sum_ext_le hM [] n
          _ ≤ 1 := hM.1
    _ = ∑' n, w n := by simp

/-- **`M(x) · 2^{-K(|x|)} ≤ 2^c · 2^{-K(x)}`**. -/
theorem univ_mul_length_le_prefixComplexityWeight {M : BitString → ℝ≥0∞}
    (hM : IsUniversalContSemimeasure M) (U : Map) (hU : IsOptimalPrefixConditional U) :
    ∃ c : ℕ, ∀ x, M x * prefixComplexityWeight U (Nat.bits x.length) ≤ 2 ^ c * prefixComplexityWeight U x := by
  -- `ν(x) = M(x) · 2^{-K(|x|)}` is a lower semicomputable discrete semimeasure.
  have hw : IsLSC₁ (fun x ↦ prefixComplexityWeight U (Nat.bits x.length)) := by
    have hRE : IsRE (fun q : BitString × ℕ ↦ KP U (Nat.bits q.1.length) [] ≤ (q.2 : ENat)) :=
      (KP_le_isRE U hU.isDecompressor).comp
        (g := fun q : BitString × ℕ ↦ (Nat.bits q.1.length, q.2))
        (Computable.pair (natBitsComputable.comp (Computable.list_length.comp Computable.fst))
          Computable.snd)
    exact (isLSC₁_complexityWeight_of_isRE (fun x ↦ KP U (Nat.bits x.length) []) hRE).congr
      (fun _ ↦ rfl)
  have hν : IsLowerSemicomputableSemimeasure
      (fun x ↦ M x * prefixComplexityWeight U (Nat.bits x.length)) := by
    refine ⟨?_, (hM.2.1.mul hw).toCond⟩
    calc ∑' x, M x * prefixComplexityWeight U (Nat.bits x.length)
        ≤ ∑' n, prefixComplexityWeight U (Nat.bits n) :=
          tsum_mul_length_weight_le hM.1 (fun n ↦ prefixComplexityWeight U (Nat.bits n))
      _ ≤ ∑' y, prefixComplexityWeight U y :=
          ENNReal.tsum_comp_le_tsum_of_injective (Function.LeftInverse.injective bitsToNat_bits) _
      _ ≤ 1 := KP_kraft_sum_le_one U hU.isPrefixDecompressor []
  obtain ⟨c, hc⟩ := lowerSemicomputableSemimeasure_le_prefixComplexityWeight hν hU
  refine ⟨c, fun x ↦ ?_⟩
  calc M x * prefixComplexityWeight U (Nat.bits x.length)
      = 2 ^ c * (2⁻¹ ^ c * (M x * prefixComplexityWeight U (Nat.bits x.length))) := by
        rw [← mul_assoc, ← ENNReal.inv_pow, ENNReal.mul_inv_cancel (two_pow_ne_zero' c) (two_pow_ne_top' c),
          one_mul]
    _ ≤ 2 ^ c * prefixComplexityWeight U x := by gcongr; exact hc x

/-- **Gács Proposition 2.3.37**, both bounds with one constant:
`2^{-K(x)} ≤ 2^c M(x)` and `M(x) 2^{-K(|x|)} ≤ 2^c 2^{-K(x)}`, i.e. `KM ≤⁺ K ≤⁺ KM + K(|x|)`. -/
theorem KM_bounds {M : BitString → ℝ≥0∞} (hM : IsUniversalContSemimeasure M) (U : Map)
    (hU : IsOptimalPrefixConditional U) :
    ∃ c : ℕ, ∀ x, prefixComplexityWeight U x ≤ 2 ^ c * M x ∧
      M x * prefixComplexityWeight U (Nat.bits x.length) ≤ 2 ^ c * prefixComplexityWeight U x := by
  obtain ⟨c₁, h₁⟩ := prefixComplexityWeight_le_univ hM U hU
  obtain ⟨c₂, h₂⟩ := univ_mul_length_le_prefixComplexityWeight hM U hU
  refine ⟨c₁ + c₂, fun x ↦ ⟨?_, ?_⟩⟩
  · exact (h₁ x).trans (mul_le_mul' (pow_le_pow_right₀ (one_le_two : (1 : ℝ≥0∞) ≤ 2) (Nat.le_add_right _ _)) le_rfl)
  · exact (h₂ x).trans (mul_le_mul' (pow_le_pow_right₀ (one_le_two : (1 : ℝ≥0∞) ≤ 2) (Nat.le_add_left _ _)) le_rfl)

end Kolmogorov.Randomness
