/-
Copyright (c) 2026 Iliad. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: stephan@iliad.ac
-/

import Gacs_Chapter_2.Randomness.Sequences

/-!
# Measures on sequences, measure of open sets, null sets (Gács §2.3.1)

* `IsSeqMeasure μ`: Gács' Definition 2.3.5, a function on strings with
  `μ(x) = μ(x0) + μ(x1)`. `ComputableSeqMeasure` adds `μ(Λ) = 1` and computability.
* `IsContSemimeasure μ`: Definition 2.3.31, `μ(Λ) ≤ 1` and `μ(x0) + μ(x1) ≤ μ(x)`.
* `ext x n`: the `2^n` extensions of `x` by `n` bits; `sum_ext_eq` is the refinement law
  `μ(x) = ∑_{|w| = n} μ(xw)`.
* `openMeasure μ Γ`: the measure of the open set generated by `Γ`, defined as the
  supremum over levels `n` of the mass of the length-`n` strings having a prefix in `Γ`.
  With this definition monotonicity in `Γ`, countable subadditivity, and the formula
  `openMeasure μ Γ = ∑_{x ∈ Γ} μ x` for prefix-free `Γ` (Gács' Definition 2.3.8 and
  Corollary 2.3.7) are elementary. Gács' Lemma 2.3.6 — the value only depends on the
  open set, not on its generators — is `openMeasure_mono_openOf`, via compactness.
* Null sets (Definition 2.3.10), constructive null sets (Definition 2.3.13), random
  sequences (Definition 2.3.14), and Proposition 2.3.12 (a countable union of null sets
  is null).
* The uniform measure `λ(x) = 2^{-|x|}` as a `ComputableSeqMeasure`.
-/

namespace Kolmogorov.Randomness

open scoped ENNReal

/-! ### Measures and semimeasures on strings -/

/-- **Measure over `Σ^ℕ`** (Gács Definition 2.3.5): additive along the binary tree. -/
def IsSeqMeasure (μ : BitString → ℝ≥0∞) : Prop :=
  ∀ x, μ x = μ (x ++ [false]) + μ (x ++ [true])

/-- **Continuous semimeasure** (Gács Definition 2.3.31). -/
def IsContSemimeasure (μ : BitString → ℝ≥0∞) : Prop :=
  μ [] ≤ 1 ∧ ∀ x, μ (x ++ [false]) + μ (x ++ [true]) ≤ μ x

/-- **Computable probability measure on sequences.** -/
structure ComputableSeqMeasure where
  /-- Mass of a cylinder. -/
  mass : BitString → ℝ≥0∞
  /-- Additivity along the tree. -/
  additive : IsSeqMeasure mass
  /-- Total mass one. -/
  root : mass [] = 1
  /-- Computable. -/
  computable : IsComputableENNReal mass

/-! ### Extensions by `n` bits -/

/-- The strings extending `x` by exactly `n` bits. -/
def ext (x : BitString) : ℕ → Finset BitString
  | 0 => {x}
  | n + 1 => ext (x ++ [false]) n ∪ ext (x ++ [true]) n

theorem mem_ext {x z : BitString} {n : ℕ} : z ∈ ext x n ↔ x <+: z ∧ z.length = x.length + n := by
  induction n generalizing x with
  | zero =>
    simp only [ext, Finset.mem_singleton, add_zero]
    constructor
    · rintro rfl; exact ⟨List.prefix_rfl, rfl⟩
    · rintro ⟨h, hl⟩; exact (h.eq_of_length hl.symm).symm
  | succ n ih =>
    simp only [ext, Finset.mem_union, ih, List.length_append, List.length_singleton]
    constructor
    · rintro (⟨h, hl⟩ | ⟨h, hl⟩)
      · exact ⟨(List.prefix_append x [false]).trans h, by omega⟩
      · exact ⟨(List.prefix_append x [true]).trans h, by omega⟩
    · rintro ⟨⟨w, rfl⟩, hl⟩
      rw [List.length_append] at hl
      obtain ⟨b, w', rfl⟩ : ∃ b w', w = b :: w' := by
        cases w with
        | nil => simp at hl
        | cons b w' => exact ⟨b, w', rfl⟩
      cases b
      · left; exact ⟨⟨w', by simp⟩, by simp at hl ⊢; omega⟩
      · right; exact ⟨⟨w', by simp⟩, by simp at hl ⊢; omega⟩

theorem ext_disjoint (x : BitString) (n : ℕ) :
    Disjoint (ext (x ++ [false]) n) (ext (x ++ [true]) n) := by
  rw [Finset.disjoint_left]
  intro z h0 h1
  obtain ⟨⟨w0, hw0⟩, _⟩ := mem_ext.mp h0
  obtain ⟨⟨w1, hw1⟩, _⟩ := mem_ext.mp h1
  have : x ++ [false] ++ w0 = x ++ [true] ++ w1 := hw0.trans hw1.symm
  simp at this

/-- **Refinement law**: `μ(x) = ∑_{|w| = n} μ(xw)` for a measure. -/
theorem sum_ext_eq {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ) (x : BitString) (n : ℕ) :
    ∑ z ∈ ext x n, μ z = μ x := by
  induction n generalizing x with
  | zero => simp [ext]
  | succ n ih =>
    simp only [ext]
    rw [Finset.sum_union (ext_disjoint x n), ih, ih, hμ x]

/-- For a continuous semimeasure the refinement law becomes an inequality. -/
theorem sum_ext_le {μ : BitString → ℝ≥0∞} (hμ : IsContSemimeasure μ) (x : BitString) (n : ℕ) :
    ∑ z ∈ ext x n, μ z ≤ μ x := by
  induction n generalizing x with
  | zero => simp [ext]
  | succ n ih =>
    simp only [ext]
    rw [Finset.sum_union (ext_disjoint x n)]
    exact (add_le_add (ih _) (ih _)).trans (hμ.2 x)

theorem ext_zero_length (n : ℕ) {z : BitString} (hz : z ∈ ext [] n) : z.length = n := by
  have := (mem_ext.mp hz).2; simpa using this

/-! ### Measure of an open set -/

open Classical in
/-- Mass at level `n` of the strings covered by `Γ`. -/
noncomputable def levelMass (μ : BitString → ℝ≥0∞) (Γ : Set BitString) (n : ℕ) : ℝ≥0∞ :=
  ∑ z ∈ ext [] n, if ∃ x ∈ Γ, x <+: z then μ z else 0

/-- **Measure of the open set generated by `Γ`** (Gács Definition 2.3.8). -/
noncomputable def openMeasure (μ : BitString → ℝ≥0∞) (Γ : Set BitString) : ℝ≥0∞ :=
  ⨆ n, levelMass μ Γ n

/-- Covered strings stay covered under extension. -/
theorem covered_of_prefix {Γ : Set BitString} {z w : BitString} (h : z <+: w)
    (hz : ∃ x ∈ Γ, x <+: z) : ∃ x ∈ Γ, x <+: w := by
  obtain ⟨x, hx, hxz⟩ := hz
  exact ⟨x, hx, hxz.trans h⟩

open Classical in
/-- Refining a covered level sum, one step. -/
theorem levelMass_ext_step {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ) (Γ : Set BitString)
    (x : BitString) (n : ℕ) :
    (∑ z ∈ ext x n, if ∃ y ∈ Γ, y <+: z then μ z else 0)
      ≤ ∑ z ∈ ext x (n + 1), if ∃ y ∈ Γ, y <+: z then μ z else 0 := by
  classical
  induction n generalizing x with
  | zero =>
    change (∑ z ∈ ({x} : Finset BitString), if ∃ y ∈ Γ, y <+: z then μ z else 0)
      ≤ ∑ z ∈ ext (x ++ [false]) 0 ∪ ext (x ++ [true]) 0, if ∃ y ∈ Γ, y <+: z then μ z else 0
    rw [Finset.sum_singleton, Finset.sum_union (ext_disjoint x 0)]
    change _ ≤ (∑ z ∈ ({x ++ [false]} : Finset BitString), if ∃ y ∈ Γ, y <+: z then μ z else 0)
      + ∑ z ∈ ({x ++ [true]} : Finset BitString), if ∃ y ∈ Γ, y <+: z then μ z else 0
    rw [Finset.sum_singleton, Finset.sum_singleton]
    by_cases hc : ∃ y ∈ Γ, y <+: x
    · rw [if_pos hc, if_pos (covered_of_prefix (List.prefix_append x [false]) hc),
        if_pos (covered_of_prefix (List.prefix_append x [true]) hc), hμ x]
    · rw [if_neg hc]; exact zero_le
  | succ n ih =>
    change (∑ z ∈ ext (x ++ [false]) n ∪ ext (x ++ [true]) n,
        if ∃ y ∈ Γ, y <+: z then μ z else 0)
      ≤ ∑ z ∈ ext (x ++ [false]) (n + 1) ∪ ext (x ++ [true]) (n + 1),
        if ∃ y ∈ Γ, y <+: z then μ z else 0
    rw [Finset.sum_union (ext_disjoint x n), Finset.sum_union (ext_disjoint x (n + 1))]
    exact add_le_add (ih _) (ih _)

theorem levelMass_mono_succ {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ) (Γ : Set BitString)
    (n : ℕ) : levelMass μ Γ n ≤ levelMass μ Γ (n + 1) :=
  levelMass_ext_step hμ Γ [] n

theorem levelMass_monotone {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ) (Γ : Set BitString) :
    Monotone (levelMass μ Γ) :=
  monotone_nat_of_le_succ (levelMass_mono_succ hμ Γ)

theorem levelMass_mono_set (μ : BitString → ℝ≥0∞) {Γ Γ' : Set BitString} (h : Γ ⊆ Γ') (n : ℕ) :
    levelMass μ Γ n ≤ levelMass μ Γ' n := by
  classical
  unfold levelMass
  refine Finset.sum_le_sum fun z _ ↦ ?_
  split_ifs with h1 h2
  · exact le_rfl
  · obtain ⟨x, hx, hxz⟩ := h1; exact absurd ⟨x, h hx, hxz⟩ h2
  all_goals exact zero_le

theorem openMeasure_mono_set (μ : BitString → ℝ≥0∞) {Γ Γ' : Set BitString} (h : Γ ⊆ Γ') :
    openMeasure μ Γ ≤ openMeasure μ Γ' :=
  iSup_mono fun n ↦ levelMass_mono_set μ h n

theorem levelMass_le_openMeasure (μ : BitString → ℝ≥0∞) (Γ : Set BitString) (n : ℕ) :
    levelMass μ Γ n ≤ openMeasure μ Γ :=
  le_iSup (levelMass μ Γ) n

/-- Level mass is at most the total mass of the generators of length `≤ n`, hence at most
`∑_{x ∈ Γ} μ x`. -/
theorem levelMass_le_tsum {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ) (Γ : Set BitString)
    (n : ℕ) : levelMass μ Γ n ≤ ∑' x, Γ.indicator μ x := by
  classical
  -- Each covered `z` of length `n` has a shortest generator prefix; group by it.
  -- Simpler: bound by the sum over generators `x` of length `≤ n` of `∑_{z ∈ ext x (n-|x|)} μ z`.
  set G : Finset BitString := (boundedPrograms n).toFinset.filter (· ∈ Γ) with hG
  have hstep : levelMass μ Γ n ≤ ∑ x ∈ G, ∑ z ∈ ext x (n - x.length), μ z := by
    unfold levelMass
    -- Every covered `z` lies in `ext x (n - |x|)` for some `x ∈ G`.
    calc ∑ z ∈ ext [] n, (if ∃ x ∈ Γ, x <+: z then μ z else 0)
        ≤ ∑ z ∈ ext [] n, ∑ x ∈ G, (if z ∈ ext x (n - x.length) then μ z else 0) := by
          refine Finset.sum_le_sum fun z hz ↦ ?_
          split_ifs with h
          · obtain ⟨x, hx, hxz⟩ := h
            have hzl := ext_zero_length n hz
            have hxG : x ∈ G := by
              rw [hG, Finset.mem_filter, List.mem_toFinset, mem_boundedPrograms_iff]
              exact ⟨by rw [← hzl]; exact hxz.length_le, hx⟩
            have hzx : z ∈ ext x (n - x.length) := mem_ext.mpr ⟨hxz, by
              have := hxz.length_le; omega⟩
            calc μ z = (if z ∈ ext x (n - x.length) then μ z else 0) := by rw [if_pos hzx]
              _ ≤ _ := Finset.single_le_sum
                  (f := fun x ↦ if z ∈ ext x (n - x.length) then μ z else 0)
                  (fun _ _ ↦ zero_le) hxG
          · exact zero_le
      _ = ∑ x ∈ G, ∑ z ∈ ext [] n, (if z ∈ ext x (n - x.length) then μ z else 0) :=
          Finset.sum_comm
      _ = ∑ x ∈ G, ∑ z ∈ ext x (n - x.length), μ z := by
          refine Finset.sum_congr rfl fun x hx ↦ ?_
          rw [← Finset.sum_filter]
          refine Finset.sum_congr ?_ (fun _ _ ↦ rfl)
          ext z
          rw [Finset.mem_filter]
          constructor
          · exact fun h ↦ h.2
          · intro h
            refine ⟨?_, h⟩
            obtain ⟨hxz, hl⟩ := mem_ext.mp h
            have hxn : x.length ≤ n := by
              rw [hG, Finset.mem_filter, List.mem_toFinset, mem_boundedPrograms_iff] at hx
              exact hx.1
            exact mem_ext.mpr ⟨List.nil_prefix, by simp; omega⟩
  calc levelMass μ Γ n ≤ ∑ x ∈ G, ∑ z ∈ ext x (n - x.length), μ z := hstep
    _ = ∑ x ∈ G, μ x := Finset.sum_congr rfl (fun x _ ↦ sum_ext_eq hμ x _)
    _ = ∑ x ∈ G, Γ.indicator μ x := Finset.sum_congr rfl (fun x hx ↦ by
        rw [hG, Finset.mem_filter] at hx
        rw [Set.indicator_of_mem hx.2])
    _ ≤ ∑' x, Γ.indicator μ x := ENNReal.sum_le_tsum G

/-- **Subadditivity over generators**: `openMeasure μ Γ ≤ ∑_{x ∈ Γ} μ x`. -/
theorem openMeasure_le_tsum {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ) (Γ : Set BitString) :
    openMeasure μ Γ ≤ ∑' x, Γ.indicator μ x :=
  iSup_le fun n ↦ levelMass_le_tsum hμ Γ n

/-- A generator contributes its full mass: `μ x ≤ openMeasure μ Γ` for `x ∈ Γ`. -/
theorem mass_le_openMeasure (μ : BitString → ℝ≥0∞) {Γ : Set BitString}
    {x : BitString} (hx : x ∈ Γ) : μ x ≤ openMeasure μ Γ := by
  classical
  refine le_trans ?_ (levelMass_le_openMeasure μ Γ x.length)
  unfold levelMass
  have hmem : x ∈ ext [] x.length := mem_ext.mpr ⟨List.nil_prefix, by simp⟩
  calc μ x = (if ∃ y ∈ Γ, y <+: x then μ x else 0) := by rw [if_pos ⟨x, hx, List.prefix_rfl⟩]
    _ ≤ _ := Finset.single_le_sum (f := fun z ↦ if ∃ y ∈ Γ, y <+: z then μ z else 0)
        (fun _ _ ↦ zero_le) hmem

/-- A finite sum of `tsum`s is the `tsum` of the finite sums (in `ℝ≥0∞`). -/
theorem finsetSum_tsum_comm {α : Type*} (s : Finset α) (f : ℕ → α → ℝ≥0∞) :
    ∑ z ∈ s, ∑' i, f i z = ∑' i, ∑ z ∈ s, f i z := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.sum_insert ha, ih, ← ENNReal.tsum_add]
    simp [Finset.sum_insert ha]

/-- **Countable subadditivity** (part of Gács Proposition 2.3.9). -/
theorem openMeasure_iUnion_le (μ : BitString → ℝ≥0∞)
    (Γ : ℕ → Set BitString) : openMeasure μ (⋃ i, Γ i) ≤ ∑' i, openMeasure μ (Γ i) := by
  classical
  refine iSup_le fun n ↦ ?_
  unfold levelMass
  calc ∑ z ∈ ext [] n, (if ∃ x ∈ ⋃ i, Γ i, x <+: z then μ z else 0)
      ≤ ∑ z ∈ ext [] n, ∑' i, (if ∃ x ∈ Γ i, x <+: z then μ z else 0) := by
        refine Finset.sum_le_sum fun z _ ↦ ?_
        split_ifs with h
        · obtain ⟨x, hx, hxz⟩ := h
          obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hx
          calc μ z = (if ∃ x ∈ Γ i, x <+: z then μ z else 0) := by rw [if_pos ⟨x, hi, hxz⟩]
            _ ≤ _ := ENNReal.le_tsum i
        · exact zero_le
    _ = ∑' i, ∑ z ∈ ext [] n, (if ∃ x ∈ Γ i, x <+: z then μ z else 0) :=
        finsetSum_tsum_comm _ _
    _ ≤ ∑' i, openMeasure μ (Γ i) :=
        ENNReal.tsum_le_tsum fun i ↦ levelMass_le_openMeasure μ (Γ i) n

/-- **Gács Lemma 2.3.6 / Proposition 2.3.9, monotonicity in the open set.** If the open set
generated by `Γ` is contained in the one generated by `Γ'`, the measures compare. Needs
compactness: a covered string of level `n` is covered by `Γ'` at some deeper level. -/
theorem openMeasure_mono_openOf {μ : BitString → ℝ≥0∞} (hμ : IsSeqMeasure μ)
    {Γ Γ' : Set BitString} (h : openOf Γ ⊆ openOf Γ') : openMeasure μ Γ ≤ openMeasure μ Γ' := by
  classical
  refine iSup_le fun n ↦ ?_
  -- For each covered `z` at level `n`, a level `n_z` where `Γ'` covers all of `cylinder z`.
  have hlev : ∀ z ∈ ext [] n, (∃ x ∈ Γ, x <+: z) →
      ∃ m, z.length ≤ m ∧ ∀ w, z <+: w → w.length = m → ∃ x ∈ Γ', x <+: w := by
    intro z _ hz
    obtain ⟨x, hx, hxz⟩ := hz
    exact exists_level_of_cylinder_subset
      ((cylinder_mono hxz).trans ((cylinder_subset_openOf hx).trans h))
  choose! lev hlev using hlev
  set m := (ext [] n).sup (fun z ↦ if ∃ x ∈ Γ, x <+: z then lev z else n) with hm
  have hnm : n ≤ m := by
    obtain ⟨z, hz⟩ : (ext [] n).Nonempty :=
      ⟨List.replicate n false, mem_ext.mpr ⟨List.nil_prefix, by simp⟩⟩
    refine le_trans ?_ (Finset.le_sup (f := fun z ↦ if ∃ x ∈ Γ, x <+: z then lev z else n) hz)
    split_ifs with hc
    · exact (ext_zero_length n hz).symm.le.trans (hlev z hz hc).1
    · exact le_rfl
  refine le_trans ?_ (levelMass_le_openMeasure μ Γ' m)
  unfold levelMass
  -- Refine level `n` to level `m`: each covered `z` splits into `ext z (m - n)`, all covered
  -- by `Γ'`.
  calc ∑ z ∈ ext [] n, (if ∃ x ∈ Γ, x <+: z then μ z else 0)
      ≤ ∑ z ∈ ext [] n, ∑ w ∈ ext z (m - n), (if ∃ x ∈ Γ', x <+: w then μ w else 0) := by
        refine Finset.sum_le_sum fun z hz ↦ ?_
        split_ifs with hc
        · rw [← sum_ext_eq hμ z (m - n)]
          refine Finset.sum_le_sum fun w hw ↦ ?_
          obtain ⟨hzw, hwl⟩ := mem_ext.mp hw
          have hzl := ext_zero_length n hz
          have hlevz : lev z ≤ m := by
            refine le_trans ?_
              (Finset.le_sup (f := fun z ↦ if ∃ x ∈ Γ, x <+: z then lev z else n) hz)
            rw [if_pos hc]
          -- `w` extends `z` to level `m ≥ lev z`; its prefix of length `lev z` is covered.
          obtain ⟨hzlev, hcov⟩ := hlev z hz hc
          have hw' : ∃ x ∈ Γ', x <+: w := by
            have hzw' : z = w.take z.length := List.prefix_iff_eq_take.mp hzw
            have hztake : z <+: w.take (lev z) := by
              rw [List.prefix_iff_eq_take, List.take_take,
                min_eq_left (by omega : z.length ≤ lev z)]
              exact hzw'
            obtain ⟨x, hx, hxw⟩ := hcov (w.take (lev z)) hztake (by simp; omega)
            exact ⟨x, hx, hxw.trans (List.take_prefix _ _)⟩
          rw [if_pos hw']
        · exact zero_le
    _ = ∑ w ∈ ext [] m, (if ∃ x ∈ Γ', x <+: w then μ w else 0) := by
        rw [← Finset.sum_biUnion]
        · congr 1
          ext w
          simp only [Finset.mem_biUnion, mem_ext, List.nil_prefix, List.length_nil, zero_add,
            true_and]
          constructor
          · rintro ⟨z, hz, hzw, hwl⟩; omega
          · intro hwl
            refine ⟨w.take n, by simp; omega, List.take_prefix _ _, by simp; omega⟩
        · intro z hz z' hz' hne
          rw [Function.onFun, Finset.disjoint_left]
          intro w hw hw'
          obtain ⟨hzw, -⟩ := mem_ext.mp hw
          obtain ⟨hz'w, -⟩ := mem_ext.mp hw'
          have h1 := ext_zero_length n hz
          have h2 := ext_zero_length n hz'
          exact hne (List.prefix_of_prefix_length_le hzw hz'w (by omega) |>.eq_of_length (by omega))

/-! ### Null sets and randomness -/

/-- **Null set** (Gács Definition 2.3.10). -/
def IsNullSet (μ : BitString → ℝ≥0∞) (N : Set Seq) : Prop :=
  ∃ G : ℕ → Set BitString, (∀ m, openMeasure μ (G m) ≤ 2⁻¹ ^ m) ∧ N ⊆ ⋂ m, openOf (G m)

/-- **Constructive null set** (Gács Definition 2.3.13): the generators are uniformly
recursively enumerable in `m`. -/
def IsConstructiveNull (μ : BitString → ℝ≥0∞) (N : Set Seq) : Prop :=
  ∃ Γ : ℕ → Set BitString, IsRE (fun p : ℕ × BitString ↦ p.2 ∈ Γ p.1) ∧
    (∀ m, openMeasure μ (Γ m) ≤ 2⁻¹ ^ m) ∧ N ⊆ ⋂ m, openOf (Γ m)

/-- **Random sequence** (Gács Definition 2.3.14): in no constructive null set. -/
def IsRandomSeq (μ : BitString → ℝ≥0∞) (ξ : Seq) : Prop :=
  ∀ N, IsConstructiveNull μ N → ξ ∉ N

theorem IsConstructiveNull.isNullSet {μ : BitString → ℝ≥0∞} {N : Set Seq}
    (h : IsConstructiveNull μ N) : IsNullSet μ N := by
  obtain ⟨Γ, _, hΓ, hN⟩ := h
  exact ⟨Γ, hΓ, hN⟩

theorem IsNullSet.mono {μ : BitString → ℝ≥0∞} {N N' : Set Seq} (h : IsNullSet μ N) (hs : N' ⊆ N) :
    IsNullSet μ N' := by
  obtain ⟨G, hG, hN⟩ := h
  exact ⟨G, hG, hs.trans hN⟩

theorem tsum_inv_two_pow_shift (m : ℕ) : ∑' i : ℕ, (2 : ℝ≥0∞)⁻¹ ^ (m + i + 1) = 2⁻¹ ^ m := by
  have h : ∀ i : ℕ, (2 : ℝ≥0∞)⁻¹ ^ (m + i + 1) = 2⁻¹ ^ (m + 1) * 2⁻¹ ^ i := fun i ↦ by
    rw [← pow_add]; congr 1; omega
  simp_rw [h]
  rw [ENNReal.tsum_mul_left, ENNReal.tsum_geometric, ENNReal.one_sub_inv_two, inv_inv, pow_succ,
    mul_assoc, ENNReal.inv_mul_cancel two_ne_zero ENNReal.ofNat_ne_top, mul_one]

/-- **Gács Proposition 2.3.12.** A countable union of null sets is a null set. -/
theorem isNullSet_iUnion (μ : BitString → ℝ≥0∞) {N : ℕ → Set Seq}
    (h : ∀ i, IsNullSet μ (N i)) : IsNullSet μ (⋃ i, N i) := by
  choose G hG hN using h
  refine ⟨fun m ↦ ⋃ i, G i (m + i + 1), fun m ↦ ?_, ?_⟩
  · calc openMeasure μ (⋃ i, G i (m + i + 1)) ≤ ∑' i, openMeasure μ (G i (m + i + 1)) :=
          openMeasure_iUnion_le μ _
      _ ≤ ∑' i, (2 : ℝ≥0∞)⁻¹ ^ (m + i + 1) := ENNReal.tsum_le_tsum fun i ↦ hG i _
      _ = 2⁻¹ ^ m := tsum_inv_two_pow_shift m
  · intro ξ hξ
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hξ
    refine Set.mem_iInter.mpr fun m ↦ ?_
    have := Set.mem_iInter.mp (hN i hi) (m + i + 1)
    exact openOf_mono (Set.subset_iUnion (fun i ↦ G i (m + i + 1)) i) this

/-! ### The uniform measure -/

/-- `2^{-n}` as a rational. -/
theorem ratVal_one_two_pow (n : ℕ) : ratVal (1, 2 ^ n) = (2 : ℝ≥0∞)⁻¹ ^ n := by
  unfold ratVal; push_cast; rw [one_div, ENNReal.inv_pow]

/-- **The uniform (coin-tossing) measure** `λ(x) = 2^{-|x|}`. -/
noncomputable def uniformSeqMeasure : ComputableSeqMeasure where
  mass x := (2 : ℝ≥0∞)⁻¹ ^ x.length
  additive x := by
    simp only [List.length_append, List.length_singleton]
    exact (inv_two_pow_succ_add_self x.length).symm
  root := by simp
  computable := by
    refine ⟨fun _ x ↦ (1, 2 ^ x.length), fun _ x ↦ (1, 2 ^ x.length),
      fun _ _ ↦ ⟨by positivity, by positivity⟩, ?_, ?_, fun k x ↦ ?_⟩
    · exact Computable.pair (Computable.const 1)
        (natPow_primrec.to_comp.comp (Computable.const 2)
          (Computable.list_length.comp Computable.snd))
    · exact Computable.pair (Computable.const 1)
        (natPow_primrec.to_comp.comp (Computable.const 2)
          (Computable.list_length.comp Computable.snd))
    · rw [ratVal_one_two_pow]
      exact ⟨le_rfl, le_rfl, le_self_add⟩

end Kolmogorov.Randomness
