/-
Copyright (c) 2026 Iliad. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: stephan@iliad.ac
-/

import Gacs_Chapter_2.Randomness.KMBounds

/-!
# Tests of randomness on sequences (Gács Definition 2.3.29, Theorem 2.3.2)

A test on sequences is carried by a function `T` on **strings**, lower semicomputable and
monotone along prefixes; its value on a sequence is `seqVal T ξ = sup_n T(ξ_{1:n})`. Every
lower semicomputable function on the Cantor space arises this way, so nothing is lost.

* `IsIntegrableSeqTest P T`: `∑_{|z| = n} P(z) T(z) ≤ 1` for all `n` (the integral of a
  monotone function is the supremum of these level sums).
* `IsMLSeqTest P T`: `P {seqVal T > 2^k} ≤ 2^{-k}`, i.e. the open set generated by
  `{z : 2^k < T z}` has measure at most `2^{-k}`.
* `IsIntegrableSeqTest.isMLSeqTest`: Markov's inequality.
* **Theorem 2.3.2**: `{ξ : seqVal T ξ = ∞}` is a constructive null set for every
  probability-bounded test (`isConstructiveNull_seqVal_top`), and every constructive
  null set is contained in `{ξ : seqVal T ξ = ∞}` for an integrable test `T`
  (`exists_integrableSeqTest_of_constructiveNull`), namely
  `T(z) = ∑_m 2^m · 1[z has a prefix in Γ_{2m+2}]`.
-/

namespace Kolmogorov.Randomness

open scoped ENNReal

/-! ### Prefixes of a sequence and values along it -/

/-- The first `n` bits of a sequence. -/
def seqTake (ξ : Seq) (n : ℕ) : BitString := List.ofFn (fun i : Fin n ↦ ξ i)

@[simp] theorem length_seqTake (ξ : Seq) (n : ℕ) : (seqTake ξ n).length = n := List.length_ofFn

theorem isPrefixOfSeq_seqTake (ξ : Seq) (n : ℕ) : IsPrefixOfSeq (seqTake ξ n) ξ := by
  intro i hi
  simp [seqTake, List.getElem_ofFn]

theorem eq_seqTake_of_isPrefixOfSeq {x : BitString} {ξ : Seq} (hx : IsPrefixOfSeq x ξ) :
    x = seqTake ξ x.length :=
  (prefix_of_isPrefixOfSeq hx (isPrefixOfSeq_seqTake ξ _) (by simp)).eq_of_length (by simp)

theorem seqTake_prefix {ξ : Seq} {m n : ℕ} (h : m ≤ n) : seqTake ξ m <+: seqTake ξ n :=
  prefix_of_isPrefixOfSeq (isPrefixOfSeq_seqTake ξ m) (isPrefixOfSeq_seqTake ξ n) (by simpa)

/-- The value of a string function along a sequence. -/
noncomputable def seqVal (T : BitString → ℝ≥0∞) (ξ : Seq) : ℝ≥0∞ := ⨆ n, T (seqTake ξ n)

theorem le_seqVal (T : BitString → ℝ≥0∞) {x : BitString} {ξ : Seq} (hx : IsPrefixOfSeq x ξ) :
    T x ≤ seqVal T ξ := by
  rw [eq_seqTake_of_isPrefixOfSeq hx]
  exact le_iSup (fun n ↦ T (seqTake ξ n)) x.length

/-- Monotone along prefixes. -/
def IsMonoStr (T : BitString → ℝ≥0∞) : Prop := ∀ x y, x <+: y → T x ≤ T y

/-! ### Prefix maxima -/

/-- `max_{y ⊑ z} f y`. -/
noncomputable def prefixMax (f : BitString → ℝ≥0∞) (z : BitString) : ℝ≥0∞ :=
  (Finset.range (z.length + 1)).sup (fun k ↦ f (z.take k))

theorem le_prefixMax (f : BitString → ℝ≥0∞) {y z : BitString} (h : y <+: z) :
    f y ≤ prefixMax f z := by
  have hy : y = z.take y.length := List.prefix_iff_eq_take.mp h
  unfold prefixMax
  rw [hy]
  exact Finset.le_sup (f := fun k ↦ f (z.take k))
    (Finset.mem_range.mpr (by have := h.length_le; omega))

theorem prefixMax_le (f : BitString → ℝ≥0∞) {z : BitString} {b : ℝ≥0∞}
    (h : ∀ y, y <+: z → f y ≤ b) : prefixMax f z ≤ b :=
  Finset.sup_le fun k _ ↦ h _ (List.take_prefix k z)

theorem prefixMax_isMonoStr (f : BitString → ℝ≥0∞) : IsMonoStr (prefixMax f) := fun _ _ hxy ↦
  prefixMax_le f fun _ hw ↦ le_prefixMax f (hw.trans hxy)

theorem le_prefixMax_self (f : BitString → ℝ≥0∞) (z : BitString) : f z ≤ prefixMax f z :=
  le_prefixMax f List.prefix_rfl

theorem dyadicValue_finset_sup (F : Finset ℕ) (hF : F.Nonempty) (g : ℕ → ℕ) (s : ℕ) :
    dyadicValue (F.sup g) s = F.sup (fun k ↦ dyadicValue (g k) s) := by
  obtain ⟨k₀, hk₀, hsup⟩ := Finset.exists_mem_eq_sup F hF g
  apply le_antisymm
  · rw [hsup]; exact Finset.le_sup (f := fun k ↦ dyadicValue (g k) s) hk₀
  · refine Finset.sup_le fun k hk ↦ ?_
    unfold dyadicValue
    gcongr
    exact_mod_cast Finset.le_sup (f := g) hk

/-- **Prefix maxima of an lsc function are lsc.** -/
theorem prefixMax_isLSC₁ {f : BitString → ℝ≥0∞} (hf : IsLSC₁ f) : IsLSC₁ (prefixMax f) := by
  obtain ⟨a, hmono, hsup, ha⟩ := hf
  refine ⟨fun s z ↦ (Finset.range (z.length + 1)).sup (fun k ↦ a s (z.take k)), fun s z ↦ ?_,
    fun z ↦ ?_, ?_⟩
  · rw [dyadicValue_finset_sup _ ⟨0, by simp⟩, dyadicValue_finset_sup _
      ⟨0, by simp⟩]
    exact Finset.sup_mono_fun fun k _ ↦ hmono s _
  · unfold prefixMax
    apply le_antisymm
    · refine iSup_le fun s ↦ ?_
      rw [dyadicValue_finset_sup _ ⟨0, by simp⟩]
      refine Finset.sup_mono_fun fun k _ ↦ ?_
      change dyadicValue (a s (z.take k)) s ≤ f (z.take k)
      rw [← hsup (z.take k)]
      exact le_iSup (fun s ↦ dyadicValue (a s (z.take k)) s) s
    · refine Finset.sup_le fun k hk ↦ ?_
      change f (z.take k) ≤ _
      rw [← hsup (z.take k)]
      refine iSup_le fun s ↦ le_iSup_of_le s ?_
      rw [dyadicValue_finset_sup _ ⟨0, by simp⟩]
      exact Finset.le_sup (f := fun k ↦ dyadicValue (a s (z.take k)) s) hk
  · have hg : Computable (fun q : (ℕ × BitString) × ℕ ↦ a q.1.1 (q.1.2.take q.2)) :=
      (ha.comp (Computable.pair (Computable.fst.comp Computable.fst)
        (primrec_list_take.to_comp.comp (Computable.snd.comp Computable.fst)
          Computable.snd))).of_eq (fun _ ↦ rfl)
    have : Computable (fun p : ℕ × BitString ↦
        (Finset.range (p.2.length + 1)).sup (fun k ↦ a p.1 (p.2.take k))) :=
      computable_finset_range_sup (fun p : ℕ × BitString ↦ p.2.length + 1)
        (fun (p : ℕ × BitString) k ↦ a p.1 (p.2.take k))
        (Computable.succ.comp (Computable.list_length.comp Computable.snd)) hg
    exact this

/-! ### Integrable and probability-bounded tests -/

/-- The level-`n` integral `∑_{|z| = n} P(z) T(z)`. -/
noncomputable def levelIntegral (P : ComputableSeqMeasure) (T : BitString → ℝ≥0∞) (n : ℕ) : ℝ≥0∞ :=
  ∑ z ∈ ext [] n, P.mass z * T z

/-- **Integrable test on sequences** (Gács Definition 2.3.29). -/
def IsIntegrableSeqTest (P : ComputableSeqMeasure) (T : BitString → ℝ≥0∞) : Prop :=
  IsLSC₁ T ∧ IsMonoStr T ∧ ∀ n, levelIntegral P T n ≤ 1

/-- **Probability-bounded (Martin-Löf) test on sequences.** -/
def IsMLSeqTest (P : ComputableSeqMeasure) (T : BitString → ℝ≥0∞) : Prop :=
  IsLSC₁ T ∧ IsMonoStr T ∧ ∀ k : ℕ, openMeasure P.mass {z | (2 : ℝ≥0∞) ^ k < T z} ≤ 2⁻¹ ^ k

/-- A universal integrable test dominates every integrable test along every sequence. -/
def IsUniversalIntegrableSeqTest (P : ComputableSeqMeasure) (T₀ : BitString → ℝ≥0∞) : Prop :=
  IsIntegrableSeqTest P T₀ ∧
    ∀ T, IsIntegrableSeqTest P T → ∃ c : ℕ, ∀ ξ, seqVal T ξ ≤ 2 ^ c * seqVal T₀ ξ

/-- **Markov's inequality on sequences**: integrable tests are probability-bounded. -/
theorem IsIntegrableSeqTest.isMLSeqTest {P : ComputableSeqMeasure} {T : BitString → ℝ≥0∞}
    (h : IsIntegrableSeqTest P T) : IsMLSeqTest P T := by
  classical
  refine ⟨h.1, h.2.1, fun k ↦ iSup_le fun n ↦ ?_⟩
  unfold levelMass
  calc ∑ z ∈ ext [] n, (if ∃ x ∈ {z | (2 : ℝ≥0∞) ^ k < T z}, x <+: z then P.mass z else 0)
      ≤ ∑ z ∈ ext [] n, P.mass z * T z * 2⁻¹ ^ k := by
        refine Finset.sum_le_sum fun z _ ↦ ?_
        split_ifs with hz
        · obtain ⟨x, hx, hxz⟩ := hz
          have hTz : (2 : ℝ≥0∞) ^ k < T z := lt_of_lt_of_le hx (h.2.1 x z hxz)
          calc P.mass z = P.mass z * (2 ^ k * 2⁻¹ ^ k) := by
                rw [← ENNReal.inv_pow,
                  ENNReal.mul_inv_cancel (two_pow_ne_zero' k) (two_pow_ne_top' k), mul_one]
            _ = P.mass z * 2 ^ k * 2⁻¹ ^ k := by ring
            _ ≤ P.mass z * T z * 2⁻¹ ^ k := mul_le_mul' (mul_le_mul' le_rfl hTz.le) le_rfl
        · exact zero_le
    _ = levelIntegral P T n * 2⁻¹ ^ k := (Finset.sum_mul _ _ _).symm
    _ ≤ 1 * 2⁻¹ ^ k := mul_le_mul' (h.2.2 n) le_rfl
    _ = 2⁻¹ ^ k := one_mul _

/-! ### Theorem 2.3.2 (a): a test's infinity set is a constructive null set -/

theorem dyadicValue_two_pow_zero (k : ℕ) : dyadicValue (2 ^ k) 0 = (2 : ℝ≥0∞) ^ k := by
  simp [dyadicValue]

/-- **Gács Theorem 2.3.2 (a).** -/
theorem isConstructiveNull_seqVal_top {P : ComputableSeqMeasure} {T : BitString → ℝ≥0∞}
    (h : IsMLSeqTest P T) : IsConstructiveNull P.mass {ξ | seqVal T ξ = ⊤} := by
  refine ⟨fun k ↦ {z | (2 : ℝ≥0∞) ^ k < T z}, ?_, h.2.2, ?_⟩
  · have hre := h.1.dyadic_lt_isRE.comp
      (g := fun p : ℕ × BitString ↦ (p.2, (2 ^ p.1, 0)))
      (Computable.pair Computable.snd (Computable.pair
        (natPow_primrec.to_comp.comp (Computable.const 2) Computable.fst) (Computable.const 0)))
    exact hre.congr (fun p ↦ by simp only [Set.mem_setOf_eq, dyadicValue_two_pow_zero])
  · intro ξ hξ
    refine Set.mem_iInter.mpr fun k ↦ ?_
    have hlt : (2 : ℝ≥0∞) ^ k < seqVal T ξ := by
      rw [Set.mem_setOf_eq] at hξ; rw [hξ]; exact lt_top_iff_ne_top.mpr (two_pow_ne_top' k)
    unfold seqVal at hlt
    obtain ⟨n, hn⟩ := lt_iSup_iff.mp hlt
    exact mem_openOf.mpr ⟨seqTake ξ n, hn, isPrefixOfSeq_seqTake ξ n⟩

/-! ### Theorem 2.3.2 (b): a constructive null set is contained in a test's infinity set -/

section NullToTest

variable (Γ : ℕ → Set BitString)

/-- Coverage: does `z` have a prefix in `Γ m`? -/
def coveredBy (m : ℕ) (z : BitString) : Prop := ∃ x ∈ Γ m, x <+: z

theorem coveredBy_mono {m : ℕ} {z z' : BitString} (h : z <+: z') (hz : coveredBy Γ m z) :
    coveredBy Γ m z' := by
  obtain ⟨x, hx, hxz⟩ := hz; exact ⟨x, hx, hxz.trans h⟩

open Classical in
/-- **The test of a constructive null set**: `∑_m 2^m · 1[z covered by Γ_{2m+2}]`. -/
noncomputable def nullTest (z : BitString) : ℝ≥0∞ :=
  ∑' m : ℕ, if coveredBy Γ (2 * m + 2) z then (2 : ℝ≥0∞) ^ m else 0

theorem nullTest_isMonoStr : IsMonoStr (nullTest Γ) := by
  classical
  intro x y hxy
  refine ENNReal.tsum_le_tsum fun m ↦ ?_
  split_ifs with h1 h2
  · exact le_rfl
  · exact absurd (coveredBy_mono Γ hxy h1) h2
  all_goals exact zero_le

/-- Detection at stage `s`: some generator of length `≤ s` of `Γ_{2m+2}` is a prefix of
`z` and its witness halts within fuel `s`. -/
def detect (c : Nat.Partrec.Code) (s m : ℕ) (z : BitString) : Bool :=
  (boundedPrograms s).any (fun x ↦ fuelHalts c s (2 * m + 2, x) && decide (x <+: z))

theorem detect_primrec (c : Nat.Partrec.Code) :
    Primrec (fun r : (ℕ × BitString) × ℕ ↦ detect c r.1.1 r.2 r.1.2) := by
  have hpred : Primrec (fun q : ((ℕ × BitString) × ℕ) × BitString ↦
      fuelHalts c q.1.1.1 (2 * q.1.2 + 2, q.2) && decide (q.2 <+: q.1.1.2)) := by
    have h1 : Primrec (fun q : ((ℕ × BitString) × ℕ) × BitString ↦
        fuelHalts c q.1.1.1 (2 * q.1.2 + 2, q.2)) :=
      (fuelHalts_primrec c).comp (Primrec.pair (Primrec.fst.comp (Primrec.fst.comp Primrec.fst))
        (Primrec.pair (Primrec.nat_add.comp (Primrec.nat_mul.comp (Primrec.const 2)
          (Primrec.snd.comp Primrec.fst)) (Primrec.const 2)) Primrec.snd))
    have h2 : Primrec (fun q : ((ℕ × BitString) × ℕ) × BitString ↦ decide (q.2 <+: q.1.1.2)) := by
      have : Primrec (fun q : ((ℕ × BitString) × ℕ) × BitString ↦
          decide (q.1.1.2.take q.2.length = q.2)) :=
        bitStringEq_primrec.comp (Primrec.pair
          (primrec_list_take.comp (Primrec.snd.comp (Primrec.fst.comp Primrec.fst))
            (Primrec.list_length.comp Primrec.snd)) Primrec.snd)
      exact this.of_eq (fun q ↦ decide_eq_decide.mpr (take_eq_iff_prefix _ _))
    exact Primrec.and.comp h1 h2
  exact list_any_primrec (f := fun r : (ℕ × BitString) × ℕ ↦ boundedPrograms r.1.1)
    (p := fun r x ↦ fuelHalts c r.1.1 (2 * r.2 + 2, x) && decide (x <+: r.1.2))
    (primrec_boundedPrograms.comp (Primrec.fst.comp Primrec.fst)) hpred.to₂

/-- Stage-`s` approximation of `nullTest`, dovetailing levels `m ≤ s`. -/
def nullTestApprox (c : Nat.Partrec.Code) (s : ℕ) (z : BitString) : ℕ :=
  ∑ m ∈ Finset.range (s + 1), if detect c s m z then 2 ^ m * 2 ^ s else 0

theorem nullTestApprox_computable (c : Nat.Partrec.Code) :
    Computable (fun p : ℕ × BitString ↦ nullTestApprox c p.1 p.2) := by
  have hterm : Computable₂ (fun (p : ℕ × BitString) (m : ℕ) ↦
      if detect c p.1 m p.2 then 2 ^ m * 2 ^ p.1 else 0) := by
    have : Primrec (fun r : (ℕ × BitString) × ℕ ↦
        if detect c r.1.1 r.2 r.1.2 then 2 ^ r.2 * 2 ^ r.1.1 else 0) :=
      (Primrec.cond (detect_primrec c) (Primrec.nat_mul.comp (natPow_primrec.comp (Primrec.const 2)
        Primrec.snd) (natPow_primrec.comp (Primrec.const 2) (Primrec.fst.comp Primrec.fst)))
        (Primrec.const 0)).of_eq (fun r ↦ by cases detect c r.1.1 r.2 r.1.2 <;> rfl)
    exact this.to_comp
  exact (computable_range_sum _ hterm (fun p ↦ p.1 + 1) (Computable.succ.comp Computable.fst)).of_eq
    (fun _ ↦ rfl)

theorem dyadic_nullTestApprox (c : Nat.Partrec.Code) (s : ℕ) (z : BitString) :
    dyadicValue (nullTestApprox c s z) s
      = ∑ m ∈ Finset.range (s + 1), if detect c s m z then (2 : ℝ≥0∞) ^ m else 0 := by
  unfold dyadicValue nullTestApprox
  rw [Nat.cast_sum]
  simp only [div_eq_mul_inv, Finset.sum_mul]
  refine Finset.sum_congr rfl fun m _ ↦ ?_
  split_ifs
  · push_cast
    rw [mul_assoc, ENNReal.mul_inv_cancel (two_pow_ne_zero' s) (two_pow_ne_top' s), mul_one]
  · simp

variable {f : ℕ × BitString →. Unit} {c : Nat.Partrec.Code}

theorem detect_mono (c : Nat.Partrec.Code) {s s' : ℕ} (h : s ≤ s') {m : ℕ} {z : BitString}
    (hd : detect c s m z = true) : detect c s' m z = true := by
  unfold detect at hd ⊢
  obtain ⟨x, hx, hpx⟩ := List.any_eq_true.mp hd
  refine List.any_eq_true.mpr ⟨x, ?_, ?_⟩
  · rw [mem_boundedPrograms_iff] at hx ⊢; omega
  · rw [Bool.and_eq_true] at hpx ⊢
    exact ⟨fuelHalts_mono c h hpx.1, hpx.2⟩

theorem detect_sound
    (hc : c.eval = fun n ↦ (Part.ofOption (Encodable.decode (α := ℕ × BitString) n)).bind
      (fun a ↦ Part.map Encodable.encode (f a)))
    (hdom : ∀ q, (f q).Dom ↔ q.2 ∈ Γ q.1) {s m : ℕ} {z : BitString}
    (hd : detect c s m z = true) : coveredBy Γ (2 * m + 2) z := by
  unfold detect at hd
  obtain ⟨x, _, hpx⟩ := List.any_eq_true.mp hd
  rw [Bool.and_eq_true, decide_eq_true_iff] at hpx
  exact ⟨x, (hdom (2 * m + 2, x)).mp (fuelHalts_sound hc hpx.1), hpx.2⟩

theorem detect_complete
    (hc : c.eval = fun n ↦ (Part.ofOption (Encodable.decode (α := ℕ × BitString) n)).bind
      (fun a ↦ Part.map Encodable.encode (f a)))
    (hdom : ∀ q, (f q).Dom ↔ q.2 ∈ Γ q.1) {m : ℕ} {z : BitString}
    (hcov : coveredBy Γ (2 * m + 2) z) : ∃ s, detect c s m z = true := by
  obtain ⟨x, hx, hxz⟩ := hcov
  obtain ⟨k, hk⟩ := fuelHalts_complete hc ((hdom (2 * m + 2, x)).mpr hx)
  refine ⟨max k x.length, List.any_eq_true.mpr ⟨x, ?_, ?_⟩⟩
  · rw [mem_boundedPrograms_iff]; exact le_max_right _ _
  · rw [Bool.and_eq_true, decide_eq_true_iff]
    exact ⟨fuelHalts_mono c (le_max_left _ _) hk, hxz⟩

/-- All levels below `n` covered are detected uniformly at some stage. -/
theorem exists_stage_detect_all
    (hc : c.eval = fun n ↦ (Part.ofOption (Encodable.decode (α := ℕ × BitString) n)).bind
      (fun a ↦ Part.map Encodable.encode (f a)))
    (hdom : ∀ q, (f q).Dom ↔ q.2 ∈ Γ q.1) (z : BitString) (n : ℕ) :
    ∃ s, n ≤ s ∧ ∀ m < n, coveredBy Γ (2 * m + 2) z → detect c s m z = true := by
  induction n with
  | zero => exact ⟨0, le_rfl, fun m hm ↦ absurd hm (Nat.not_lt_zero m)⟩
  | succ n ih =>
    obtain ⟨s, hs, hall⟩ := ih
    by_cases hcov : coveredBy Γ (2 * n + 2) z
    · obtain ⟨s', hs'⟩ := detect_complete Γ hc hdom hcov
      refine ⟨max (max s s') (n + 1), le_max_right _ _, fun m hm hm' ↦ ?_⟩
      rcases Nat.lt_succ_iff_lt_or_eq.mp hm with h | h
      · exact detect_mono c ((le_max_left s s').trans (le_max_left _ _)) (hall m h hm')
      · subst h; exact detect_mono c ((le_max_right s s').trans (le_max_left _ _)) hs'
    · refine ⟨max s (n + 1), le_max_right _ _, fun m hm hm' ↦ ?_⟩
      rcases Nat.lt_succ_iff_lt_or_eq.mp hm with h | h
      · exact detect_mono c (le_max_left _ _) (hall m h hm')
      · subst h; exact absurd hm' hcov

/-- **`nullTest` is lower semicomputable.** -/
theorem nullTest_isLSC₁
    (hc : c.eval = fun n ↦ (Part.ofOption (Encodable.decode (α := ℕ × BitString) n)).bind
      (fun a ↦ Part.map Encodable.encode (f a)))
    (hdom : ∀ q, (f q).Dom ↔ q.2 ∈ Γ q.1) : IsLSC₁ (nullTest Γ) := by
  classical
  refine ⟨nullTestApprox c, fun s z ↦ ?_, fun z ↦ ?_, nullTestApprox_computable c⟩
  · rw [dyadic_nullTestApprox, dyadic_nullTestApprox]
    calc ∑ m ∈ Finset.range (s + 1), (if detect c s m z then (2 : ℝ≥0∞) ^ m else 0)
        ≤ ∑ m ∈ Finset.range (s + 1), (if detect c (s + 1) m z then (2 : ℝ≥0∞) ^ m else 0) := by
          refine Finset.sum_le_sum fun m _ ↦ ?_
          split_ifs with h1 h2
          · exact le_rfl
          · exact absurd (detect_mono c (Nat.le_succ s) h1) (by simpa using h2)
          all_goals exact zero_le
      _ ≤ _ := Finset.sum_le_sum_of_subset (Finset.range_mono (Nat.le_succ _))
  · simp only [dyadic_nullTestApprox]
    unfold nullTest
    apply le_antisymm
    · refine iSup_le fun s ↦ ?_
      calc ∑ m ∈ Finset.range (s + 1), (if detect c s m z then (2 : ℝ≥0∞) ^ m else 0)
          ≤ ∑ m ∈ Finset.range (s + 1),
              (if coveredBy Γ (2 * m + 2) z then (2 : ℝ≥0∞) ^ m else 0) := by
            refine Finset.sum_le_sum fun m _ ↦ ?_
            split_ifs with h1 h2
            · exact le_rfl
            · exact absurd (detect_sound Γ hc hdom h1) h2
            all_goals exact zero_le
        _ ≤ _ := ENNReal.sum_le_tsum _
    · rw [ENNReal.tsum_eq_iSup_nat]
      refine iSup_le fun n ↦ ?_
      obtain ⟨s, hns, hall⟩ := exists_stage_detect_all Γ hc hdom z n
      refine le_iSup_of_le s ?_
      calc ∑ m ∈ Finset.range n, (if coveredBy Γ (2 * m + 2) z then (2 : ℝ≥0∞) ^ m else 0)
          ≤ ∑ m ∈ Finset.range n, (if detect c s m z then (2 : ℝ≥0∞) ^ m else 0) := by
            refine Finset.sum_le_sum fun m hm ↦ ?_
            split_ifs with h1 h2
            · exact le_rfl
            · exact absurd (hall m (Finset.mem_range.mp hm) h1) (by simpa using h2)
            all_goals exact zero_le
        _ ≤ _ := Finset.sum_le_sum_of_subset
          (Finset.range_mono (hns.trans (Nat.le_succ s)))

/-- **The level integrals of `nullTest` are at most one.** -/
theorem levelIntegral_nullTest_le (P : ComputableSeqMeasure)
    (hmeas : ∀ m, openMeasure P.mass (Γ m) ≤ 2⁻¹ ^ m) (n : ℕ) :
    levelIntegral P (nullTest Γ) n ≤ 1 := by
  classical
  unfold levelIntegral nullTest
  calc ∑ z ∈ ext [] n, P.mass z * ∑' m, (if coveredBy Γ (2 * m + 2) z then (2 : ℝ≥0∞) ^ m else 0)
      = ∑ z ∈ ext [] n, ∑' m,
          (2 : ℝ≥0∞) ^ m * (if coveredBy Γ (2 * m + 2) z then P.mass z else 0) := by
        refine Finset.sum_congr rfl fun z _ ↦ ?_
        rw [← ENNReal.tsum_mul_left]
        refine tsum_congr fun m ↦ ?_
        split_ifs <;> simp [mul_comm]
    _ = ∑' m, (2 : ℝ≥0∞) ^ m * levelMass P.mass (Γ (2 * m + 2)) n := by
        rw [finsetSum_tsum_comm]
        refine tsum_congr fun m ↦ ?_
        unfold levelMass coveredBy
        rw [Finset.mul_sum]
    _ ≤ ∑' m, (2 : ℝ≥0∞) ^ m * 2⁻¹ ^ (2 * m + 2) :=
        ENNReal.tsum_le_tsum fun m ↦ mul_le_mul' le_rfl
          ((levelMass_le_openMeasure _ _ n).trans (hmeas _))
    _ = ∑' m, (2 : ℝ≥0∞)⁻¹ ^ (1 + m + 1) := by
        refine tsum_congr fun m ↦ ?_
        rw [show 2 * m + 2 = m + (m + 2) by ring, pow_add, ← mul_assoc, ← ENNReal.inv_pow,
          ENNReal.mul_inv_cancel (two_pow_ne_zero' m) (two_pow_ne_top' m), one_mul]
        congr 1; ring
    _ = 2⁻¹ ^ 1 := tsum_inv_two_pow_shift 1
    _ ≤ 1 := pow_le_one₀ zero_le (ENNReal.inv_le_one.mpr one_le_two)

theorem eq_top_of_forall_two_pow_le {v : ℝ≥0∞} (h : ∀ K : ℕ, (2 : ℝ≥0∞) ^ K ≤ v) : v = ⊤ := by
  by_contra hv
  obtain ⟨K, hK⟩ := ENNReal.exists_nat_gt hv
  have : (K : ℝ≥0∞) ≤ 2 ^ K := by exact_mod_cast (Nat.lt_two_pow_self (n := K)).le
  exact absurd (this.trans (h K)) (not_le.mpr hK)

/-- Uniform prefix: a sequence in all `openOf (Γ m)` has a single prefix covered by
`Γ 0, …, Γ K`. -/
theorem exists_seqTake_coveredBy_all {ξ : Seq} (hξ : ∀ m, ξ ∈ openOf (Γ m)) (K : ℕ) :
    ∃ n, ∀ m ≤ K, coveredBy Γ m (seqTake ξ n) := by
  induction K with
  | zero =>
    obtain ⟨x, hx, hxξ⟩ := mem_openOf.mp (hξ 0)
    refine ⟨x.length, fun m hm ↦ ?_⟩
    obtain rfl : m = 0 := by omega
    exact ⟨x, hx, by rw [← eq_seqTake_of_isPrefixOfSeq hxξ]⟩
  | succ K ih =>
    obtain ⟨n, hn⟩ := ih
    obtain ⟨x, hx, hxξ⟩ := mem_openOf.mp (hξ (K + 1))
    refine ⟨max n x.length, fun m hm ↦ ?_⟩
    rcases Nat.lt_succ_iff_lt_or_eq.mp (Nat.lt_succ_of_le hm) with h | h
    · exact coveredBy_mono Γ (seqTake_prefix (le_max_left _ _)) (hn m (Nat.lt_succ_iff.mp h))
    · subst h
      refine ⟨x, hx, ?_⟩
      have hx' : x = seqTake ξ x.length := eq_seqTake_of_isPrefixOfSeq hxξ
      calc x = seqTake ξ x.length := hx'
        _ <+: seqTake ξ (max n x.length) := seqTake_prefix (le_max_right n x.length)

/-- On the null set, `nullTest` is infinite along the sequence. -/
theorem seqVal_nullTest_eq_top {ξ : Seq} (hξ : ∀ m, ξ ∈ openOf (Γ m)) :
    seqVal (nullTest Γ) ξ = ⊤ := by
  classical
  refine eq_top_of_forall_two_pow_le fun K ↦ ?_
  obtain ⟨n, hn⟩ := exists_seqTake_coveredBy_all Γ hξ (2 * K + 2)
  refine le_trans ?_ (le_iSup (fun n ↦ nullTest Γ (seqTake ξ n)) n)
  unfold nullTest
  calc (2 : ℝ≥0∞) ^ K = (if coveredBy Γ (2 * K + 2) (seqTake ξ n) then (2 : ℝ≥0∞) ^ K else 0) := by
        rw [if_pos (hn (2 * K + 2) le_rfl)]
    _ ≤ _ := ENNReal.le_tsum K

/-- **Gács Theorem 2.3.2 (b).** Every constructive null set lies in the infinity set of an
integrable test. -/
theorem exists_integrableSeqTest_of_constructiveNull (P : ComputableSeqMeasure) {N : Set Seq}
    (h : IsConstructiveNull P.mass N) :
    ∃ T, IsIntegrableSeqTest P T ∧ N ⊆ {ξ | seqVal T ξ = ⊤} := by
  obtain ⟨Γ, ⟨f, hf, hdom⟩, hmeas, hN⟩ := h
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hf
  refine ⟨nullTest Γ, ⟨nullTest_isLSC₁ Γ hc hdom, nullTest_isMonoStr Γ,
    levelIntegral_nullTest_le Γ P hmeas⟩, fun ξ hξ ↦ ?_⟩
  exact seqVal_nullTest_eq_top Γ (fun m ↦ Set.mem_iInter.mp (hN hξ) m)

end NullToTest

end Kolmogorov.Randomness
