/-
Copyright (c) 2026 Iliad. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: stephan@iliad.ac
-/

import Gacs_Chapter_2.Randomness.LSCAlgebra
import Mathlib.Topology.Constructions
import Mathlib.Topology.Compactness.Compact

/-!
# Infinite binary sequences, cylinders, and compactness (Gács §2.3.1, Definition 2.3.1)

The space is `Seq := ℕ → Bool`. A string `x` is a prefix of `ξ` when `ξ` agrees with `x`
on the first `|x|` positions; the **cylinder** `cylinder x` is the set of such `ξ`, and an
**open set** is a union of cylinders, given here by its set of generating strings
(`openOf Γ`). This is Gács' Definition 2.3.1 with open sets carried by generators, as the
strategy prescribes: every theorem of §2.3 is a statement about strings.

The one topological fact the chapter needs is compactness: a cylinder covered by
cylinders is covered by finitely many of them, hence, at a suitable level `n`, every
length-`n` extension of the base string has a generator as prefix
(`exists_level_of_cylinder_subset`). Rather than reproving König's lemma (Gács' proof of
Lemma 2.3.6), we take it from Mathlib: `ℕ → Bool` is compact by Tychonoff, and cylinders
are closed and open.
-/

namespace Kolmogorov.Randomness

/-- Infinite binary sequences. -/
abbrev Seq := ℕ → Bool

/-- `x` is a prefix of the sequence `ξ`. -/
def IsPrefixOfSeq (x : BitString) (ξ : Seq) : Prop := ∀ i (h : i < x.length), x[i] = ξ i

/-- The cylinder set of `x`: all sequences beginning with `x`. -/
def cylinder (x : BitString) : Set Seq := {ξ | IsPrefixOfSeq x ξ}

/-- The open set generated by a set of strings. -/
def openOf (Γ : Set BitString) : Set Seq := ⋃ x ∈ Γ, cylinder x

theorem mem_cylinder {x : BitString} {ξ : Seq} : ξ ∈ cylinder x ↔ IsPrefixOfSeq x ξ := Iff.rfl

theorem mem_openOf {Γ : Set BitString} {ξ : Seq} : ξ ∈ openOf Γ ↔ ∃ x ∈ Γ, IsPrefixOfSeq x ξ := by
  simp [openOf, cylinder]

theorem isPrefixOfSeq_nil (ξ : Seq) : IsPrefixOfSeq [] ξ := fun _ h ↦ absurd h (by simp)

theorem IsPrefixOfSeq.of_prefix {x y : BitString} (h : x <+: y) {ξ : Seq}
    (hy : IsPrefixOfSeq y ξ) : IsPrefixOfSeq x ξ := fun i hi ↦
  (h.getElem hi).trans (hy i (hi.trans_le h.length_le))

theorem cylinder_mono {x y : BitString} (h : x <+: y) : cylinder y ⊆ cylinder x :=
  fun _ hξ ↦ hξ.of_prefix h

theorem openOf_mono {Γ Γ' : Set BitString} (h : Γ ⊆ Γ') : openOf Γ ⊆ openOf Γ' :=
  Set.biUnion_subset_biUnion_left h

theorem cylinder_subset_openOf {Γ : Set BitString} {x : BitString} (hx : x ∈ Γ) :
    cylinder x ⊆ openOf Γ :=
  Set.subset_biUnion_of_mem (u := fun x ↦ cylinder x) hx

/-- The sequence extending `w` by zeros. -/
def padSeq (w : BitString) : Seq := fun i ↦ w.getD i false

theorem isPrefixOfSeq_padSeq (w : BitString) : IsPrefixOfSeq w (padSeq w) := fun i hi ↦ by
  unfold padSeq
  rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hi]
  rfl

/-- Two prefixes of one sequence are comparable. -/
theorem prefix_of_isPrefixOfSeq {x y : BitString} {ξ : Seq} (hx : IsPrefixOfSeq x ξ)
    (hy : IsPrefixOfSeq y ξ) (hl : x.length ≤ y.length) : x <+: y := by
  rw [List.prefix_iff_eq_take]
  apply List.ext_getElem (by simp; omega)
  intro i h1 h2
  rw [List.getElem_take, hx i h1, hy i (by omega)]

/-- Distinct members of a prefix-free set have disjoint cylinders. -/
theorem disjoint_cylinder_of_prefixFree {S : Set BitString} (hS : IsPrefixFree S) {x y : BitString}
    (hx : x ∈ S) (hy : y ∈ S) (hxy : x ≠ y) : Disjoint (cylinder x) (cylinder y) := by
  rw [Set.disjoint_left]
  intro ξ hξx hξy
  rcases le_total x.length y.length with h | h
  · exact hxy (hS hx hy (prefix_of_isPrefixOfSeq hξx hξy h))
  · exact hxy (hS hy hx (prefix_of_isPrefixOfSeq hξy hξx h)).symm

/-! ### Topology: cylinders are clopen, hence compact -/

theorem cylinder_eq_pi (x : BitString) :
    cylinder x = Set.pi (↑(Finset.range x.length) : Set ℕ)
      (fun i ↦ {b | ∀ h : i < x.length, x[i] = b}) := by
  ext ξ
  simp only [cylinder, IsPrefixOfSeq, Set.mem_setOf_eq, Set.mem_pi, Finset.mem_coe,
    Finset.mem_range]
  constructor
  · intro h i hi _; exact h i hi
  · intro h i hi; exact h i hi hi

theorem isOpen_cylinder (x : BitString) : IsOpen (cylinder x) := by
  rw [cylinder_eq_pi]
  exact isOpen_set_pi (Finset.finite_toSet _) (fun _ _ ↦ isOpen_discrete _)

theorem isClosed_cylinder (x : BitString) : IsClosed (cylinder x) := by
  rw [cylinder_eq_pi]
  exact isClosed_set_pi (fun _ _ ↦ isClosed_discrete _)

theorem isCompact_cylinder (x : BitString) : IsCompact (cylinder x) :=
  (isClosed_cylinder x).isCompact

theorem isOpen_openOf (Γ : Set BitString) : IsOpen (openOf Γ) :=
  isOpen_biUnion (fun x _ ↦ isOpen_cylinder x)

/-- **Compactness of cylinders** (the content of Gács' Lemma 2.3.6). If the cylinder of `z`
is covered by the cylinders of `Γ`, then at some level `n ≥ |z|` every extension of `z` of
length `n` has a prefix in `Γ`. -/
theorem exists_level_of_cylinder_subset {z : BitString} {Γ : Set BitString}
    (h : cylinder z ⊆ openOf Γ) :
    ∃ n, z.length ≤ n ∧ ∀ w : BitString, z <+: w → w.length = n → ∃ x ∈ Γ, x <+: w := by
  have hcov : cylinder z ⊆ ⋃ x : Γ, cylinder (x : BitString) := by
    intro ξ hξ
    obtain ⟨x, hxΓ, hx⟩ := mem_openOf.mp (h hξ)
    exact Set.mem_iUnion.mpr ⟨⟨x, hxΓ⟩, hx⟩
  obtain ⟨t, ht⟩ := (isCompact_cylinder z).elim_finite_subcover
    (fun x : Γ ↦ cylinder (x : BitString)) (fun x ↦ isOpen_cylinder _) hcov
  refine ⟨max z.length (t.sup (fun x ↦ (x : BitString).length)), le_max_left _ _,
    fun w hzw hw ↦ ?_⟩
  have hξ : padSeq w ∈ cylinder z := (isPrefixOfSeq_padSeq w).of_prefix hzw
  obtain ⟨x, hxt, hxξ⟩ : ∃ x ∈ t, padSeq w ∈ cylinder (x : BitString) := by
    simpa using ht hξ
  refine ⟨x, x.2, prefix_of_isPrefixOfSeq hxξ (isPrefixOfSeq_padSeq w) ?_⟩
  rw [hw]
  exact (Finset.le_sup (f := fun x : Γ ↦ (x : BitString).length) hxt).trans (le_max_right _ _)

end Kolmogorov.Randomness
